# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/toast/Documents/School/Spring2021/CPSC326/project-jlunder00

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/toast/Documents/School/Spring2021/CPSC326/project-jlunder00

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toast/Documents/School/Spring2021/CPSC326/project-jlunder00/CMakeFiles /home/toast/Documents/School/Spring2021/CPSC326/project-jlunder00/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toast/Documents/School/Spring2021/CPSC326/project-jlunder00/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw1

# Build rule for target.
hw1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw1
.PHONY : hw1

# fast build rule for target.
hw1/fast:
	$(MAKE) -f CMakeFiles/hw1.dir/build.make CMakeFiles/hw1.dir/build
.PHONY : hw1/fast

#=============================================================================
# Target rules for targets named hw2

# Build rule for target.
hw2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw2
.PHONY : hw2

# fast build rule for target.
hw2/fast:
	$(MAKE) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/build
.PHONY : hw2/fast

#=============================================================================
# Target rules for targets named hw3

# Build rule for target.
hw3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw3
.PHONY : hw3

# fast build rule for target.
hw3/fast:
	$(MAKE) -f CMakeFiles/hw3.dir/build.make CMakeFiles/hw3.dir/build
.PHONY : hw3/fast

#=============================================================================
# Target rules for targets named hw5

# Build rule for target.
hw5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw5
.PHONY : hw5

# fast build rule for target.
hw5/fast:
	$(MAKE) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/build
.PHONY : hw5/fast

#=============================================================================
# Target rules for targets named mypl

# Build rule for target.
mypl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mypl
.PHONY : mypl

# fast build rule for target.
mypl/fast:
	$(MAKE) -f CMakeFiles/mypl.dir/build.make CMakeFiles/mypl.dir/build
.PHONY : mypl/fast

hw1.o: hw1.cpp.o

.PHONY : hw1.o

# target to build an object file
hw1.cpp.o:
	$(MAKE) -f CMakeFiles/hw1.dir/build.make CMakeFiles/hw1.dir/hw1.cpp.o
.PHONY : hw1.cpp.o

hw1.i: hw1.cpp.i

.PHONY : hw1.i

# target to preprocess a source file
hw1.cpp.i:
	$(MAKE) -f CMakeFiles/hw1.dir/build.make CMakeFiles/hw1.dir/hw1.cpp.i
.PHONY : hw1.cpp.i

hw1.s: hw1.cpp.s

.PHONY : hw1.s

# target to generate assembly for a file
hw1.cpp.s:
	$(MAKE) -f CMakeFiles/hw1.dir/build.make CMakeFiles/hw1.dir/hw1.cpp.s
.PHONY : hw1.cpp.s

hw2.o: hw2.cpp.o

.PHONY : hw2.o

# target to build an object file
hw2.cpp.o:
	$(MAKE) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/hw2.cpp.o
.PHONY : hw2.cpp.o

hw2.i: hw2.cpp.i

.PHONY : hw2.i

# target to preprocess a source file
hw2.cpp.i:
	$(MAKE) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/hw2.cpp.i
.PHONY : hw2.cpp.i

hw2.s: hw2.cpp.s

.PHONY : hw2.s

# target to generate assembly for a file
hw2.cpp.s:
	$(MAKE) -f CMakeFiles/hw2.dir/build.make CMakeFiles/hw2.dir/hw2.cpp.s
.PHONY : hw2.cpp.s

hw3.o: hw3.cpp.o

.PHONY : hw3.o

# target to build an object file
hw3.cpp.o:
	$(MAKE) -f CMakeFiles/hw3.dir/build.make CMakeFiles/hw3.dir/hw3.cpp.o
.PHONY : hw3.cpp.o

hw3.i: hw3.cpp.i

.PHONY : hw3.i

# target to preprocess a source file
hw3.cpp.i:
	$(MAKE) -f CMakeFiles/hw3.dir/build.make CMakeFiles/hw3.dir/hw3.cpp.i
.PHONY : hw3.cpp.i

hw3.s: hw3.cpp.s

.PHONY : hw3.s

# target to generate assembly for a file
hw3.cpp.s:
	$(MAKE) -f CMakeFiles/hw3.dir/build.make CMakeFiles/hw3.dir/hw3.cpp.s
.PHONY : hw3.cpp.s

hw5.o: hw5.cpp.o

.PHONY : hw5.o

# target to build an object file
hw5.cpp.o:
	$(MAKE) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/hw5.cpp.o
.PHONY : hw5.cpp.o

hw5.i: hw5.cpp.i

.PHONY : hw5.i

# target to preprocess a source file
hw5.cpp.i:
	$(MAKE) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/hw5.cpp.i
.PHONY : hw5.cpp.i

hw5.s: hw5.cpp.s

.PHONY : hw5.s

# target to generate assembly for a file
hw5.cpp.s:
	$(MAKE) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/hw5.cpp.s
.PHONY : hw5.cpp.s

hw6.o: hw6.cpp.o

.PHONY : hw6.o

# target to build an object file
hw6.cpp.o:
	$(MAKE) -f CMakeFiles/mypl.dir/build.make CMakeFiles/mypl.dir/hw6.cpp.o
.PHONY : hw6.cpp.o

hw6.i: hw6.cpp.i

.PHONY : hw6.i

# target to preprocess a source file
hw6.cpp.i:
	$(MAKE) -f CMakeFiles/mypl.dir/build.make CMakeFiles/mypl.dir/hw6.cpp.i
.PHONY : hw6.cpp.i

hw6.s: hw6.cpp.s

.PHONY : hw6.s

# target to generate assembly for a file
hw6.cpp.s:
	$(MAKE) -f CMakeFiles/mypl.dir/build.make CMakeFiles/mypl.dir/hw6.cpp.s
.PHONY : hw6.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... hw1"
	@echo "... edit_cache"
	@echo "... hw2"
	@echo "... rebuild_cache"
	@echo "... hw3"
	@echo "... hw5"
	@echo "... mypl"
	@echo "... hw1.o"
	@echo "... hw1.i"
	@echo "... hw1.s"
	@echo "... hw2.o"
	@echo "... hw2.i"
	@echo "... hw2.s"
	@echo "... hw3.o"
	@echo "... hw3.i"
	@echo "... hw3.s"
	@echo "... hw5.o"
	@echo "... hw5.i"
	@echo "... hw5.s"
	@echo "... hw6.o"
	@echo "... hw6.i"
	@echo "... hw6.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

